### ISSUE TITLE
Longhorn frontend on SSL

### ISSUE THREAD

**Issue by arthef** [tigase/k8s-scripts#12]
From reading the `cluster-longhorn.sh` script, it seems that longhorn frontend is exposed on plain HTTP. What would it take to have it working over HTTPS?

**Comment by hantu85** [comment]
@arturhefczyc I think that we've addressed that in b14716c6a15476793715d5a4e952a8acfd17f1ec

**Comment by arthef** [comment]
It is not solved yet.
Longhorn forntend is available on HTTPS, which is better than HTTP but it is only a self-signed certificate and generates warnings.
Plus it is available on IP address of the LB only, not on the domain name.

TBH, I do not know how to make it available on the domain address with SSL certificate. I also wonder, if, for example, we have a few services exposed on the same domain like:
https://example.com/lh/ (longhorn)
https://example.com/  (webmail)
https://example.com/admin/ (mailu admin)

can we have a single SSL certificate for the domain or every service would request separate certificate during installation?

Please look at it.
